name: CI-CD Flask App
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
 
    - name: Build Docker Image
      run: docker build -t flask-app .
 
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker stop flask-app || true
          docker rm flask-app || true
          docker build -t flask-app .
          docker run -d --name flask-app -p 5000:5000 flask-app
